routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PenggunaController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\GaleriController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\IklanController;
use App\Http\Controllers\Admin\PertandinganController;
use App\Http\Controllers\Admin\LatihanController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\AnggotaController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\PendaftaranController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\SponsorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\PasswordController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\User\FrontendController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // $role = Role::find(2);
//     // $role->givePermissionTo('manajemen permissions');
//     return view('welcome');
// });

// Frontend
Route::get('/', [FrontendController::class, 'index']);
Route::get('/daftar-anggota', [FrontendController::class, 'anggota'])->name('daftar-anggota');
Route::get('/blog', [FrontendController::class, 'blog'])->name('blog');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::get('/jadwal-pertandingan-latihan', [FrontendController::class, 'jadwal'])->name('jadwal-pertandingan-latihan');
Route::get('/galeri', [FrontendController::class, 'galeri'])->name('galeri');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/store', [FrontendController::class, 'store'])->name('store');


Auth::routes(['verify' => true]);

Route::middleware(['has.role'])->prefix('home')->middleware('auth')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::prefix('admin')->group(function () {
        Route::prefix('manajemen-user')->middleware('permission:manajemen permission', 'verified')->group(function () {
            // Role
            Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
            Route::post('roles/create', [RoleController::class, 'store'])->name('roles.create');
            Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
            Route::put('roles/{role}/edit', [RoleController::class, 'update']);
            // Permission
            Route::get('', [PermissionController::class, 'index'])->name('permissions.index');
            Route::post('create', [PermissionController::class, 'store'])->name('permissions.create');
            Route::get('{permission}/edit', [PermissionController::class, 'edit'])->name('permissions.edit');
            Route::put('{permission}/edit', [PermissionController::class, 'update']);
            // Assign Permission
            Route::get('assignable', [AssignController::class, 'create'])->name('assign.create');
            Route::post('assignable', [AssignController::class, 'store']);
            Route::get('assignable/{role}/edit', [AssignController::class, 'edit'])->name('assign.edit');
            Route::put('assignable/{role}/edit', [AssignController::class, 'update']);
            // Permission to User
            Route::get('assign/user', [UserController::class, 'create'])->name('assign.user.create');
            Route::post('assign/user', [UserController::class, 'store']);
            Route::get('assign/{user}/user', [UserController::class, 'edit'])->name('assign.user.edit');
            Route::put('assign/{user}/user', [UserController::class, 'update']);
            // Setting user
            Route::resource('users', PenggunaController::class);
        });
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:slide permission')->group(function () {
        // Slide
        Route::resource('slide', SlideController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:galeri permission')->group(function () {
        // Galeri
        Route::resource('galeri', GaleriController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:blog permission')->group(function () {
        // Blog
        Route::resource('blog', BlogController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:iklan permission')->group(function () {
        // iklan
        Route::resource('iklan', IklanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:jadwal permission')->group(function () {
        // Jadwal pertandingan
        Route::resource('pertandingan', PertandinganController::class);
        // Jadwal latihan
        Route::resource('latihan', LatihanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:store permission')->group(function () {
        // store
        Route::resource('store', StoreController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:anggota permission')->group(function () {
        // daftar anggota
        Route::resource('anggota', AnggotaController::class);
        // cetak PDF anggota
        Route::get('cetak_pdf', [AnggotaController::class, 'cetak_pdf'])->name('anggota.cetakpdf');
        // cetak Excel anggota
        Route::get('cetak_excel', [AnggotaController::class, 'cetak_excel'])->name('anggota.cetakexcel');
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:setting permission')->group(function () {
        // settings about
        Route::resource('about', AboutController::class);
        // settings about
        Route::resource('footer', FooterController::class);
        // settings pendaftaran
        Route::resource('pendaftaran', PendaftaranController::class);
        // settings logo
        Route::resource('logo', LogoController::class);
        // settings Sponsor
        Route::resource('sponsor', SponsorController::class);
    });
});


// Profile All
Route::prefix('home')->middleware('auth', 'verified')->group(function () {
    Route::resource('profile', ProfileController::class);
    Route::get('password/edit', [PasswordController::class, 'edit'])->name('password.edit');
    Route::put('password/update', [PasswordController::class, 'update'])->name('password.update');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'foto',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function index()
    {
        $permissions = Permission::orderBy('created_at','DESC')->paginate(5);
        $permission = new Permission;
        return view('permission.permissions.index', compact('permissions', 'permission'));
    }


    public function store()
    {
        request()->validate([
            'name' => 'required',

        ]);

        Permission::create([
            'name' => request('name'),
            'guard_name' => request('guard_name') ?? 'web',
        ]);
        Alert::success('Berhasil', 'Data Berhasil Di Tambahkan');
        return back();
    }


    public function edit(Permission $permission)
    {
        abort_if(Gate::denies('edit'), Response::HTTP_FORBIDDEN, 'Forbidden');

        return view('permission.permissions.edit', [
            'permission' => $permission,
            'submit' => 'Update'
        ]);
    }


    public function update(Permission $permission)
    {
        request()->validate([
            'name' => 'required',
        ]);

        $permission->update([
            'name' => request('name'),
            'guard_name' => request('guard_name') ?? 'web',
        ]);
        Alert::info('Berhasil', 'Data Berhasil Di Update');
        return redirect()->route('permissions.index');
    }

    public function destroy($permission)
    {
        //
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }


    public function create()
    {
        abort_if(Gate::denies('create'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $roles = Role::get();
        $users = User::has('roles')->get();
        return view('permission.assign.user.create', compact('roles', 'users'));
    }



    public function store()
    {
        $user = User::where('email', request('email'))->first();
        $user->assignRole(request('roles'));
        Alert::success('Berhasil', 'Data Berhasil Di Tambahkan');
        return back();
    }


    public function edit(User $user)
    {
        abort_if(Gate::denies('edit'), Response::HTTP_FORBIDDEN, 'Forbidden');

        return view('permission.assign.user.edit', [
            'user' => $user,
            'roles' => Role::get(),
            'users' => User::has('roles')->get(),
        ]);
    }


    public function update(User $user)
    {
        $user->syncRoles(request('roles'));
        Alert::info('Berhasil', 'Data Berhasil Di Update');
        return redirect()->route('assign.user.create');
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use RealRashid\SweetAlert\Facades\Alert;
use App\Http\Controllers\Controller;
use App\Models\Blog;
use App\Models\Galeri;
use App\Models\Iklan;
use App\Models\Pertandingan;
use App\Models\Store;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blogs = Blog::all();
        $galeris = Galeri::all();
        $pertandingans = Pertandingan::orderBy('created_at','DESC')->limit('1');
        $iklans = Iklan::orderBy('created_at','DESC')->limit('1')->get();
        $stores = Store::orderBy('created_at','DESC')->limit('1')->get();
        $postinganTerbaru = Blog::orderBy('created_at','DESC')->limit('3')->get();
        return view('dashboard',[
            'blogs' => $blogs,
            'galeris' => $galeris,
            'stores' => $stores,
            'pertandingans' => $pertandingans,
            'iklans' => $iklans,
            'postinganTerbaru' => $postinganTerbaru,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/PasswordController.php
<?php

namespace App\Http\Controllers\User;

use RealRashid\SweetAlert\Facades\Alert;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\ValidationException;

class PasswordController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit()
    {
        return view('profile.password.edit');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        request()->validate([
            'current_password' => ['required'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        if(Hash::check($request->current_password, auth()->user()->password)){
            auth()->user()->update(['password' => Hash::make($request->password)]);
            Alert::info('Berhasil', 'Data Berhasil Di Update');
            return back();
        }

        throw ValidationException::withMessages([
            'current_password' => 'Your password does not match with our record',
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/permission/users/create.blade.php
@extends('layouts.master')

@section('title', 'Create User')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Create User</div>
                        <a href="{{ route('users.index') }}" class="btn btn-warning btn-sm ml-auto">Kembali</a>

 					</div>
				</div>
                <form method="POST" action="{{ route('users.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="required col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" >

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="required col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="required col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="new-password">

                            @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password-confirm" class="required col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                        <div class="col-md-6">
                            <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required autocomplete="new-password">
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-sm btn-primary">
                                {{ __('Create') }}
                            </button>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/permission/users/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit User')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit User</div>
                        <a href="{{ route('users.index') }}" class="btn btn-warning btn-sm ml-auto">Kembali</a>

 					</div>
				</div>
                <form method="POST" action="{{ route('users.update', $user->id ) }}" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="required col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name', $user->name) }}" required autocomplete="name" >

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="required col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email', $user->email) }}" required autocomplete="email">

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="password" class="required col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                        <div class="col-md-6">
                            <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" autocomplete="new-password">

                            @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="foto" class="required col-md-4 col-form-label text-md-right">{{ __('Foto') }}</label>

                        <div class="col-md-6">
                            <input type="file" name="foto" class="form-control" >
                            <br>
                            <label for="foto">Gambar Saat Ini</label><br>
                            <img src="{{ asset('storage/'. $user->foto) }}"width="50" height="50"  class="rounded-circle">

                            @error('foto')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-sm btn-primary">
                                {{ __('Update') }}
                            </button>
                        </div>
                    </div>
                </form>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/permission/users/index.blade.php
@extends('layouts.master')

@section('title', 'Data User')

@section('content')

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
	<div class="row">
		<div class="col-md-12">
			<div class="card full-height">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Tabel Data User</div>
                        @can('create')
                        <a href="{{ route('users.create') }}" class="btn btn-primary btn-sm ml-auto">Create</a>
                        @endcan
 					</div>
				</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Roles</th>
                                <th>Foto</th>
                                <th>Action</th>
                            </tr>

                            @foreach ($users as $index => $user)
                                <tr>
                                    <td>{{ $index + $users->firstItem() }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>{{ implode(', ', $user->getRoleNames()->toArray() )}}</td>
                                    <td>
                                        <img src="{{ asset('storage/'. $user->foto) }}" width="50" height="50"  class="rounded-circle"></td>
                                    <td>
                                        @can('edit')
                                        <a href="{{ route('users.edit', $user->id ) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit"></i></a>
                                        @endcan
                                        {{-- <a href="" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a> --}}
                                        @can('delete')
                                        <form action="{{ route('users.destroy', $user->id ) }}" class="d-inline-block" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" onclick="return confirm('Are you sure delete {{ $user->name }}?')" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></button>
                                        </form>
                                        @endcan
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
            {{ $users->links() }}

                </div>
			</div>
		</div>
	</div>
</div>

@endsection