routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PenggunaController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\GaleriController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\IklanController;
use App\Http\Controllers\Admin\PertandinganController;
use App\Http\Controllers\Admin\LatihanController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\AnggotaController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\PendaftaranController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\SponsorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\PasswordController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\User\FrontendController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // $role = Role::find(2);
//     // $role->givePermissionTo('manajemen permissions');
//     return view('welcome');
// });

// Frontend
Route::get('/', [FrontendController::class, 'index']);
Route::get('/daftar-anggota', [FrontendController::class, 'anggota'])->name('daftar-anggota');
Route::get('/blog', [FrontendController::class, 'blog'])->name('blog');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::get('/jadwal-pertandingan-latihan', [FrontendController::class, 'jadwal'])->name('jadwal-pertandingan-latihan');
Route::get('/galeri', [FrontendController::class, 'galeri'])->name('galeri');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/store', [FrontendController::class, 'store'])->name('store');


Auth::routes(['verify' => true]);

Route::middleware(['has.role'])->prefix('home')->middleware('auth')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::prefix('admin')->group(function () {
        Route::prefix('manajemen-user')->middleware('permission:manajemen permission', 'verified')->group(function () {
            // Role
            Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
            Route::post('roles/create', [RoleController::class, 'store'])->name('roles.create');
            Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
            Route::put('roles/{role}/edit', [RoleController::class, 'update']);
            // Permission
            Route::get('', [PermissionController::class, 'index'])->name('permissions.index');
            Route::post('create', [PermissionController::class, 'store'])->name('permissions.create');
            Route::get('{permission}/edit', [PermissionController::class, 'edit'])->name('permissions.edit');
            Route::put('{permission}/edit', [PermissionController::class, 'update']);
            // Assign Permission
            Route::get('assignable', [AssignController::class, 'create'])->name('assign.create');
            Route::post('assignable', [AssignController::class, 'store']);
            Route::get('assignable/{role}/edit', [AssignController::class, 'edit'])->name('assign.edit');
            Route::put('assignable/{role}/edit', [AssignController::class, 'update']);
            // Permission to User
            Route::get('assign/user', [UserController::class, 'create'])->name('assign.user.create');
            Route::post('assign/user', [UserController::class, 'store']);
            Route::get('assign/{user}/user', [UserController::class, 'edit'])->name('assign.user.edit');
            Route::put('assign/{user}/user', [UserController::class, 'update']);
            // Setting user
            Route::resource('users', PenggunaController::class);
        });
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:slide permission')->group(function () {
        // Slide
        Route::resource('slide', SlideController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:galeri permission')->group(function () {
        // Galeri
        Route::resource('galeri', GaleriController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:blog permission')->group(function () {
        // Blog
        Route::resource('blog', BlogController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:iklan permission')->group(function () {
        // iklan
        Route::resource('iklan', IklanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:jadwal permission')->group(function () {
        // Jadwal pertandingan
        Route::resource('pertandingan', PertandinganController::class);
        // Jadwal latihan
        Route::resource('latihan', LatihanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:store permission')->group(function () {
        // store
        Route::resource('store', StoreController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:anggota permission')->group(function () {
        // daftar anggota
        Route::resource('anggota', AnggotaController::class);
        // cetak PDF anggota
        Route::get('cetak_pdf', [AnggotaController::class, 'cetak_pdf'])->name('anggota.cetakpdf');
        // cetak Excel anggota
        Route::get('cetak_excel', [AnggotaController::class, 'cetak_excel'])->name('anggota.cetakexcel');
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:setting permission')->group(function () {
        // settings about
        Route::resource('about', AboutController::class);
        // settings about
        Route::resource('footer', FooterController::class);
        // settings pendaftaran
        Route::resource('pendaftaran', PendaftaranController::class);
        // settings logo
        Route::resource('logo', LogoController::class);
        // settings Sponsor
        Route::resource('sponsor', SponsorController::class);
    });
});


// Profile All
Route::prefix('home')->middleware('auth', 'verified')->group(function () {
    Route::resource('profile', ProfileController::class);
    Route::get('password/edit', [PasswordController::class, 'edit'])->name('password.edit');
    Route::put('password/update', [PasswordController::class, 'update'])->name('password.update');
});

app/Models/Latihan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Latihan extends Model
{
    use HasFactory;

    protected $table = 'latihans';

    protected $fillable = [
        'tempat', 'tanggal_waktu',
    ];

    protected $hidden = [];
}

app/Http/Controllers/Admin/LatihanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use App\Models\Latihan;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;

class LatihanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $latihans = Latihan::orderBy('created_at','DESC')->paginate(5);
        return view('latihan.index', compact('latihans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('create'), Response::HTTP_FORBIDDEN, 'Forbidden');

        return view('latihan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'tempat' => 'required',
            'tanggal_waktu' => 'required',
        ]);

        Latihan::create([
            'tempat' => request('tempat'),
            'tanggal_waktu' => request('tanggal_waktu'),
        ]);

        return redirect()->route('latihan.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort_if(Gate::denies('edit'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $latihans = Latihan::findOrFail($id);
        return view('latihan.edit', compact('latihans'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $data['tempat'] = ($request->tempat);
        $data['tanggal_waktu'] = ($request->tanggal_waktu);


        $latihans = Latihan::findOrFail($id);
        $latihans->update($data);

        Alert::info('Berhasil', 'Data Berhasil Di Update');
        return redirect()->route('latihan.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        abort_if(Gate::denies('delete'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $latihans = Latihan::find($id);

        $latihans->delete();
        Alert::success('Berhasil', 'Data Berhasil Di Hapus');
        return redirect()->route('latihan.index');
    }
}

resources/views/latihan/create.blade.php
@extends('layouts.master')

@section('title', 'Create Jadwal')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Create Latihan</div>
                        <a href="{{ route('latihan.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('latihan.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="tempat">Tempat</label>
                            <input type="text" name="tempat" class="form-control" id="tempat" placeholder="Enter Tempat Latihan">
                        </div>
                        <div class="form-group">
                            <label for="tanggal_waktu">Jam & Tanggal</label>
                            <input type="datetime-local" name="tanggal_waktu" id="tanggal_waktu" class="form-control" required></input>
                        </div>
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        <button class="btn btn-danger btn-sm" type="reset">Reset</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/latihan/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Jadwal')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit Latihan</div>
                        <a href="{{ route('latihan.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('latihan.update', $latihans->id ) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="tempat">Tempat</label>
                            <input type="text" name="tempat" class="form-control" id="tempat" value="{{ $latihans->tempat }}" placeholder="Enter Tempat Latihan">
                        </div>
                        <div class="form-group">
                            <label for="tanggal_waktu">Jam & Tanggal</label>
                            <input type="datetime-local" name="tanggal_waktu" id="tanggal_waktu" value="{{ $latihans->tanggal_waktu }}" class="form-control" required></input>
                        </div>
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/latihan/index.blade.php
@extends('layouts.master')

@section('title', 'Jadwal Latihan')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Jadwal Latihan</div>
                        @can('create')
                        <a href="{{ route('latihan.create') }}" class="btn btn-primary btn-sm ml-auto">Ceate</a>
                        @endcan
 					</div>
				</div>
                <div class="card-body">
                    @if (Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session('success') }}
                        </div>
                    @endif
					<div class="table-responsive">
                    <table class="table table-border">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Tempat</th>
                                <th>Tanggal dan Waktu</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($latihans as $index => $row)
                            <tr>
                                <td>{{ $index + 1 }}</td>
                                <td>{{ $row->tempat }}</td>
                                <td>{{date('d M Y H:i',strtotime($row->tanggal_waktu))}}</td>
                                <td>
                                    @can('edit')
                                    <a href="{{ route('latihan.edit', $row->id) }}"
                                        class="btn btn-warning btn-sm"><i class="fas fa-pen"></i>
                                    </a>
                                    @endcan

                                    @can('delete')
                                    <form action="{{ route('latihan.destroy',$row->id) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                    @endcan

                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">Data Masih Kosong</td>
                            </tr>
                            @endforelse

                        </tbody>
                    </table>
					</div>
                {{ $latihans->links() }}
				</div>
            </div>
        </div>
</div>


@endsection