routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PenggunaController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\GaleriController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\IklanController;
use App\Http\Controllers\Admin\PertandinganController;
use App\Http\Controllers\Admin\LatihanController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\AnggotaController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\PendaftaranController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\SponsorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\PasswordController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\User\FrontendController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // $role = Role::find(2);
//     // $role->givePermissionTo('manajemen permissions');
//     return view('welcome');
// });

// Frontend
Route::get('/', [FrontendController::class, 'index']);
Route::get('/daftar-anggota', [FrontendController::class, 'anggota'])->name('daftar-anggota');
Route::get('/blog', [FrontendController::class, 'blog'])->name('blog');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::get('/jadwal-pertandingan-latihan', [FrontendController::class, 'jadwal'])->name('jadwal-pertandingan-latihan');
Route::get('/galeri', [FrontendController::class, 'galeri'])->name('galeri');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/store', [FrontendController::class, 'store'])->name('store');


Auth::routes(['verify' => true]);

Route::middleware(['has.role'])->prefix('home')->middleware('auth')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::prefix('admin')->group(function () {
        Route::prefix('manajemen-user')->middleware('permission:manajemen permission', 'verified')->group(function () {
            // Role
            Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
            Route::post('roles/create', [RoleController::class, 'store'])->name('roles.create');
            Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
            Route::put('roles/{role}/edit', [RoleController::class, 'update']);
            // Permission
            Route::get('', [PermissionController::class, 'index'])->name('permissions.index');
            Route::post('create', [PermissionController::class, 'store'])->name('permissions.create');
            Route::get('{permission}/edit', [PermissionController::class, 'edit'])->name('permissions.edit');
            Route::put('{permission}/edit', [PermissionController::class, 'update']);
            // Assign Permission
            Route::get('assignable', [AssignController::class, 'create'])->name('assign.create');
            Route::post('assignable', [AssignController::class, 'store']);
            Route::get('assignable/{role}/edit', [AssignController::class, 'edit'])->name('assign.edit');
            Route::put('assignable/{role}/edit', [AssignController::class, 'update']);
            // Permission to User
            Route::get('assign/user', [UserController::class, 'create'])->name('assign.user.create');
            Route::post('assign/user', [UserController::class, 'store']);
            Route::get('assign/{user}/user', [UserController::class, 'edit'])->name('assign.user.edit');
            Route::put('assign/{user}/user', [UserController::class, 'update']);
            // Setting user
            Route::resource('users', PenggunaController::class);
        });
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:slide permission')->group(function () {
        // Slide
        Route::resource('slide', SlideController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:galeri permission')->group(function () {
        // Galeri
        Route::resource('galeri', GaleriController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:blog permission')->group(function () {
        // Blog
        Route::resource('blog', BlogController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:iklan permission')->group(function () {
        // iklan
        Route::resource('iklan', IklanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:jadwal permission')->group(function () {
        // Jadwal pertandingan
        Route::resource('pertandingan', PertandinganController::class);
        // Jadwal latihan
        Route::resource('latihan', LatihanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:store permission')->group(function () {
        // store
        Route::resource('store', StoreController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:anggota permission')->group(function () {
        // daftar anggota
        Route::resource('anggota', AnggotaController::class);
        // cetak PDF anggota
        Route::get('cetak_pdf', [AnggotaController::class, 'cetak_pdf'])->name('anggota.cetakpdf');
        // cetak Excel anggota
        Route::get('cetak_excel', [AnggotaController::class, 'cetak_excel'])->name('anggota.cetakexcel');
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:setting permission')->group(function () {
        // settings about
        Route::resource('about', AboutController::class);
        // settings about
        Route::resource('footer', FooterController::class);
        // settings pendaftaran
        Route::resource('pendaftaran', PendaftaranController::class);
        // settings logo
        Route::resource('logo', LogoController::class);
        // settings Sponsor
        Route::resource('sponsor', SponsorController::class);
    });
});


// Profile All
Route::prefix('home')->middleware('auth', 'verified')->group(function () {
    Route::resource('profile', ProfileController::class);
    Route::get('password/edit', [PasswordController::class, 'edit'])->name('password.edit');
    Route::put('password/update', [PasswordController::class, 'update'])->name('password.update');
});

app/Models/Pertandingan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pertandingan extends Model
{
    use HasFactory;

    protected $table = 'pertandingans';

    protected $fillable = [
        'gambar_team1','gambar_team2','nama_team1','nama_team2', 'tanggal_waktu',
    ];

    protected $hidden = [];
}

app/Http/Controllers/Admin/PertandinganController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use RealRashid\SweetAlert\Facades\Alert;
use App\Models\Pertandingan;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;

class PertandinganController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pertandingans = Pertandingan::orderBy('created_at','DESC')->paginate(5);
        return view('pertandingan.index', compact('pertandingans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        abort_if(Gate::denies('create'), Response::HTTP_FORBIDDEN, 'Forbidden');

        return view('pertandingan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'gambar_team1' => 'required|mimes:jpg,jpeg,png,bmp',
            'gambar_team2' => 'required|mimes:jpg,jpeg,png,bmp',

        ]);

        if (!empty($request->file('gambar_team1', 'gambar_team2'))) {
            $data = $request->all();
            $data['gambar_team1'] = $request->file('gambar_team1')->store('pertandingan');
            $data['gambar_team2'] = $request->file('gambar_team2')->store('pertandingan');

            Pertandingan::create($data);

            Alert::success('Berhasil', 'Data Berhasil Di Tambahkan');
            return redirect()->route('pertandingan.index');
        }else{
            $data = $request->all();
            Pertandingan::create($data);

            Alert::success('Berhasil', 'Data Berhasil Di Tambahkan');
            return redirect()->route('pertandingan.index');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        abort_if(Gate::denies('edit'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $pertandingans = Pertandingan::findOrFail($id);
        return view('pertandingan.edit', compact('pertandingans'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (empty($request->file('gambar_team1','gambar_team2'))) {
            $pertandingans = Pertandingan::find($id);
            $pertandingans->update([
                'nama_team1'=> $request->nama_team1,
                'nama_team2'=> $request->nama_team2,
                'tanggal_waktu'=> $request->tangal_waktu,
            ]);
            Alert::info('Berhasil', 'Data Berhasil Di Update');
            return redirect()->route('pertandingan.index');

        } else{
            $pertandingans = Pertandingan::find($id);
            Storage::delete([$pertandingans->gambar_team1, $pertandingans->gambar_team2 ]);
            $pertandingans->update([
                'nama_team1'=> $request->nama_team1,
                'nama_team2'=> $request->nama_team2,
                'tanggal_waktu'=> $request->tangal_waktu,
                'gambar_team1' => $request->file('gambar_team1')->store('pertandingan'),
                'gambar_team2' => $request->file('gambar_team2')->store('pertandingan'),
            ]);
            Alert::info('Berhasil', 'Data Berhasil Di Update');
            return redirect()->route('pertandingan.index');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        abort_if(Gate::denies('delete'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $pertandingans = Pertandingan::find($id);

        Storage::delete($pertandingans->gambar_team1);
        Storage::delete($pertandingans->gambar_team2);
        $pertandingans->delete();
        Alert::success('Berhasil', 'Data Berhasil Di Hapus');
        return redirect()->route('pertandingan.index');
    }
}

resources/views/pertandingan/create.blade.php
@extends('layouts.master')

@section('title', 'Create Jadwal')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Create Pertandingan</div>
                        <a href="{{ route('pertandingan.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('pertandingan.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="gambar">Gambar Team 1</label>
                            <input type="file" name="gambar_team1" class="form-control"></input>
                        </div>
                        <div class="form-group">
                            <label for="gambar">Gambar Team 2</label>
                            <input type="file" name="gambar_team2" class="form-control"></input>
                        </div>
                        <div class="form-group">
                            <label for="nama_team1">Nama Team 1</label>
                            <input type="text" name="nama_team1" class="form-control" id="nama_team1" placeholder="Enter Nama Team 1">
                        </div>
                        <div class="form-group">
                            <label for="nama_team1]2">Nama Team 2</label>
                            <input type="text" name="nama_team2" class="form-control" id="nama_team2" placeholder="Enter Nama Team 2">
                        </div>
                        <div class="form-group">
                            <label for="tanggal_waktu">Jam & Tanggal</label>
                            <input type="datetime-local" name="tanggal_waktu" id="tanggal_waktu" class="form-control" required></input>
                        </div>
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        <button class="btn btn-danger btn-sm" type="reset">Reset</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/pertandingan/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Pertandingan')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Edit Pertandingan</div>
                        <a href="{{ route('pertandingan.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('pertandingan.update', $pertandingans->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="gambar">Gambar Team 1</label>
                            <input type="file" name="gambar_team1" class="form-control"></input>
                            <br>
                            <label for="gambar">Gambar Team 1 Saat Ini</label><br>
                            <img src="{{ asset('storage/'. $pertandingans->gambar_team1) }}" width="100">
                        </div>
                        <div class="form-group">
                            <label for="gambar">Gambar Team 2</label>
                            <input type="file" name="gambar_team2" class="form-control"></input>
                            <br>
                            <label for="gambar">Gambar Team 2 Saat Ini</label><br>
                            <img src="{{ asset('storage/'. $pertandingans->gambar_team2) }}" width="100">
                        </div>
                        <div class="form-group">
                            <label for="nama_team1">Nama Team 1</label>
                            <input type="text" name="nama_team1" class="form-control" id="nama_team1" value="{{ $pertandingans->nama_team1 }}" placeholder="Enter Nama Team 1">
                        </div>
                        <div class="form-group">
                            <label for="nama_team1]2">Nama Team 2</label>
                            <input type="text" name="nama_team2" class="form-control" id="nama_team2" value="{{ $pertandingans->nama_team2 }}" placeholder="Enter Nama Team 2">
                        </div>
                        <div class="form-group">
                            <label for="tanggal_waktu">Jam & Tanggal</label>
                            <input type="datetime-local" name="tanggal_waktu" id="tanggal_waktu" class="form-control" value="{{ $pertandingans->tanggal_waktu }}" required></input>
                        </div>
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/pertandingan/index.blade.php
@extends('layouts.master')

@section('title', 'Jadwal Pertandingan')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Jadwal Pertandingan</div>
                        @can('create')
                        <a href="{{ route('pertandingan.create') }}" class="btn btn-primary btn-sm ml-auto">Ceate</a>
                        @endcan
 					</div>
				</div>
                <div class="card-body">
                    @if (Session::has('success'))
                        <div class="alert alert-success">
                            {{ Session('success') }}
                        </div>
                    @endif
					<div class="table-responsive">
                    <table class="table table-border">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Gambar Team 1</th>
                                <th>Gambar Team 2</th>
                                <th>Nama Team 1</th>
                                <th>Nama Team 2</th>
                                <th>Tanggal dan Waktu</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($pertandingans as $index => $row)
                            <tr>
                                <td>{{ $index + 1 }}</td>
                                <td><img src="{{ asset('storage/'. $row->gambar_team1) }}" width="100"></td>
                                <td><img src="{{ asset('storage/'. $row->gambar_team2) }}" width="100"></td>
                                <td>{{ $row->nama_team1 }}</td>
                                <td>{{ $row->nama_team2 }}</td>
                                <td>{{date('d M Y H:i',strtotime($row->tanggal_waktu))}}</td>
                                <td>
                                    @can('edit')
                                    <a href="{{ route('pertandingan.edit', $row->id) }}"
                                        class="btn btn-warning btn-sm"><i class="fas fa-pen"></i>
                                    </a>
                                    @endcan

                                    @can('delete')
                                    <form action="{{ route('pertandingan.destroy',$row->id) }}" method="POST" class="d-inline">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                    @endcan
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="6" class="text-center">Data Masih Kosong</td>
                            </tr>
                            @endforelse

                        </tbody>
                    </table>
					</div>

				</div>
            </div>
        </div>
</div>


@endsection