routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\AssignController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PenggunaController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\GaleriController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\IklanController;
use App\Http\Controllers\Admin\PertandinganController;
use App\Http\Controllers\Admin\LatihanController;
use App\Http\Controllers\Admin\StoreController;
use App\Http\Controllers\Admin\AnggotaController;
use App\Http\Controllers\Admin\AboutController;
use App\Http\Controllers\Admin\FooterController;
use App\Http\Controllers\Admin\PendaftaranController;
use App\Http\Controllers\Admin\LogoController;
use App\Http\Controllers\Admin\SponsorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\User\ProfileController;
use App\Http\Controllers\User\PasswordController;
use App\Http\Controllers\User\DashboardController;
use App\Http\Controllers\User\FrontendController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     // $role = Role::find(2);
//     // $role->givePermissionTo('manajemen permissions');
//     return view('welcome');
// });

// Frontend
Route::get('/', [FrontendController::class, 'index']);
Route::get('/daftar-anggota', [FrontendController::class, 'anggota'])->name('daftar-anggota');
Route::get('/blog', [FrontendController::class, 'blog'])->name('blog');
Route::get('/blog/detail/{slug}', [FrontendController::class, 'detail'])->name('detail');
Route::get('/jadwal-pertandingan-latihan', [FrontendController::class, 'jadwal'])->name('jadwal-pertandingan-latihan');
Route::get('/galeri', [FrontendController::class, 'galeri'])->name('galeri');
Route::get('/about', [FrontendController::class, 'about'])->name('about');
Route::get('/store', [FrontendController::class, 'store'])->name('store');


Auth::routes(['verify' => true]);

Route::middleware(['has.role'])->prefix('home')->middleware('auth')->group(function () {
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::prefix('admin')->group(function () {
        Route::prefix('manajemen-user')->middleware('permission:manajemen permission', 'verified')->group(function () {
            // Role
            Route::get('roles', [RoleController::class, 'index'])->name('roles.index');
            Route::post('roles/create', [RoleController::class, 'store'])->name('roles.create');
            Route::get('roles/{role}/edit', [RoleController::class, 'edit'])->name('roles.edit');
            Route::put('roles/{role}/edit', [RoleController::class, 'update']);
            // Permission
            Route::get('', [PermissionController::class, 'index'])->name('permissions.index');
            Route::post('create', [PermissionController::class, 'store'])->name('permissions.create');
            Route::get('{permission}/edit', [PermissionController::class, 'edit'])->name('permissions.edit');
            Route::put('{permission}/edit', [PermissionController::class, 'update']);
            // Assign Permission
            Route::get('assignable', [AssignController::class, 'create'])->name('assign.create');
            Route::post('assignable', [AssignController::class, 'store']);
            Route::get('assignable/{role}/edit', [AssignController::class, 'edit'])->name('assign.edit');
            Route::put('assignable/{role}/edit', [AssignController::class, 'update']);
            // Permission to User
            Route::get('assign/user', [UserController::class, 'create'])->name('assign.user.create');
            Route::post('assign/user', [UserController::class, 'store']);
            Route::get('assign/{user}/user', [UserController::class, 'edit'])->name('assign.user.edit');
            Route::put('assign/{user}/user', [UserController::class, 'update']);
            // Setting user
            Route::resource('users', PenggunaController::class);
        });
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:slide permission')->group(function () {
        // Slide
        Route::resource('slide', SlideController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:galeri permission')->group(function () {
        // Galeri
        Route::resource('galeri', GaleriController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:blog permission')->group(function () {
        // Blog
        Route::resource('blog', BlogController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:iklan permission')->group(function () {
        // iklan
        Route::resource('iklan', IklanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:jadwal permission')->group(function () {
        // Jadwal pertandingan
        Route::resource('pertandingan', PertandinganController::class);
        // Jadwal latihan
        Route::resource('latihan', LatihanController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:store permission')->group(function () {
        // store
        Route::resource('store', StoreController::class);
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:anggota permission')->group(function () {
        // daftar anggota
        Route::resource('anggota', AnggotaController::class);
        // cetak PDF anggota
        Route::get('cetak_pdf', [AnggotaController::class, 'cetak_pdf'])->name('anggota.cetakpdf');
        // cetak Excel anggota
        Route::get('cetak_excel', [AnggotaController::class, 'cetak_excel'])->name('anggota.cetakexcel');
    });
});
Route::middleware(['has.role'])->prefix('home/admin')->middleware('auth', 'verified')->group(function () {
    Route::middleware('permission:setting permission')->group(function () {
        // settings about
        Route::resource('about', AboutController::class);
        // settings about
        Route::resource('footer', FooterController::class);
        // settings pendaftaran
        Route::resource('pendaftaran', PendaftaranController::class);
        // settings logo
        Route::resource('logo', LogoController::class);
        // settings Sponsor
        Route::resource('sponsor', SponsorController::class);
    });
});


// Profile All
Route::prefix('home')->middleware('auth', 'verified')->group(function () {
    Route::resource('profile', ProfileController::class);
    Route::get('password/edit', [PasswordController::class, 'edit'])->name('password.edit');
    Route::put('password/update', [PasswordController::class, 'update'])->name('password.update');
});

app/Models/Anggota.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Anggota extends Model
{
    use HasFactory;

    protected $table = 'anggotas';

    protected $fillable = [
        'nama','jabatan','body','foto_anggota',
    ];

    protected $hidden = [];

}

app/Http/Controllers/Admin/AnggotaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\AnggotaExport;
use RealRashid\SweetAlert\Facades\Alert;
use App\Http\Controllers\Controller;
use App\Models\Anggota;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use PDF;


class AnggotaController extends Controller
{
    /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function index()
    {
        $anggotas = Anggota::orderBy('created_at','DESC')->paginate(5);
        return view('anggota.index', compact('anggotas'));
    }

    /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
    public function create()
    {
        abort_if(Gate::denies('create'), Response::HTTP_FORBIDDEN, 'Forbidden');

        return view('anggota.create');
    }

    /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama' => 'required|min:4',
            'jabatan' => 'required|min:4',
            'body' => 'required|min:4',
        ]);

        $data = $request->all();
        $data['nama'] = ($request->nama);
        $data['jabatan'] = ($request->jabatan);
        $data['body'] = ($request->body);
        $data['foto_anggota'] = $request->file('foto_anggota')->store('anggota');

        Anggota::create($data);

        Alert::success('Berhasil', 'Data Berhasil Di Tambahkan');
        return redirect()->route('anggota.index');
    }

    /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function show($id)
    {
        //
    }

    /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function edit($id)
    {
        abort_if(Gate::denies('edit'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $anggotas = Anggota::findOrFail($id);
        return view('anggota.edit', compact('anggotas'));
    }

    /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function update(Request $request, $id)
    {
        if (empty($request->file('foto_anggota'))) {
            $anggotas = Anggota::find($id);
            $anggotas->update([
                'nama'=> $request->nama,
                'jabatan'=> $request->jabatan,
                'body'=> $request->body,

            ]);
            Alert::info('Berhasil', 'Data Berhasil Di Update');
            return redirect()->route('anggota.index');

        } else{
            $anggotas = Anggota::find($id);
            Storage::delete($anggotas->gambar_artikel);
            $anggotas->update([
                'nama'=> $request->nama,
                'jabatan'=> $request->jabatan,
                'body'=> $request->body,
                'foto_anggota' => $request->file('foto_anggota')->store('anggota'),
            ]);
            Alert::info('Berhasil', 'Data Berhasil Di Update');
            return redirect()->route('anggota.index');
        }
    }

    /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
    public function destroy($id)
    {
        abort_if(Gate::denies('delete'), Response::HTTP_FORBIDDEN, 'Forbidden');

        $anggotas = Anggota::find($id);

        Storage::delete($anggotas->foto_anggota);
        $anggotas->delete();
        Alert::success('Berhasil', 'Data Berhasil Di Hapus');
        return redirect()->route('anggota.index');
    }



    // export PDF
    public function cetak_pdf() {

        $anggotas = Anggota::all();

        $pdf = PDF::loadView('anggota.cetak',[
            'anggotas' => $anggotas,
        ]);

        $options = [
            'dpi' => 96,
            'defaultFont' => 'Nunito',
            'isRemoteEnabled' => true
        ];

        $pdf->setOptions($options);
        // return $pdf->download('Daftar Anggota.pdf');
        return $pdf->stream('Daftar Anggota.pdf');
    }


    public function cetak_excel()
	{
		return Excel::download(new AnggotaExport(), 'Daftar Anggota.xlsx');
	}
}

resources/views/anggota/cetak.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Hi</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Nama Anggota</th>
            <th>Jabatan</th>
            <th>Deskripsi</th>
            {{-- <th>Gambar</th> --}}
        </tr>
        @foreach ( $anggotas as $index => $row )
        <tr>
            <td>{{ $index + 1}}</td>
            <td>{{ $row->nama }}</td>
            <td>{{ $row->jabatan }}</td>
            <td>{{ $row->body }}</td>
            {{-- <td><img src="{{ public_path('storage/'. $row->foto_anggota) }}" width="100"></td> --}}
        </tr>
        @endforeach

    </table>

    {{-- <h1>{{$anggotas}}</h1> --}}
</body>
</html>

resources/views/anggota/create.blade.php
@extends('layouts.master')

@section('title', 'Create Anggota')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Create Anggota</div>
                        <a href="{{ route('anggota.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('anggota.store') }}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="nama">Nama Anggota</label>
                            <input type="text" name="nama" class="form-control" id="text" placeholder="Enter Nama Anggota">
                        </div>
                        <div class="form-group">
                            <label for="jabatan">Jabatan</label>
                            <input type="text" name="jabatan" class="form-control" id="text" placeholder="Enter Jabatan Anggota">
                        </div>
                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea name="body" id="text" class="form-control" placeholder="Isi dengan biodata anda"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="foto">Foto Anggota</label>
                            <input type="file" name="foto_anggota" class="form-control"></input>
                        </div>
                        <div class="form-group">
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        <button class="btn btn-danger btn-sm" type="reset">Reset</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/anggota/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit Anggota')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
	<div class="page-inner py-5">
		<div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
			<div>

			</div>
			<div class="ml-md-auto py-2 py-md-0">
			</div>
		</div>
	</div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
					<div class="card-head-row">
						<div class="card-title">Create Anggota</div>
                        <a href="{{ route('anggota.index') }}" class="btn btn-warning btn-sm ml-auto">Back</a>
 					</div>
				</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('anggota.update', $anggotas->id) }}" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="nama">Nama Anggota</label>
                            <input type="text" name="nama" class="form-control" value="{{ $anggotas->nama }}" id="text" placeholder="Enter Nama Anggota">
                        </div>
                        <div class="form-group">
                            <label for="jabatan">Jabatan</label>
                            <input type="text" name="jabatan" class="form-control" id="text" value="{{ $anggotas->jabatan }}" placeholder="Enter Jabatan Anggota">
                        </div>
                        <div class="form-group">
                            <label for="deskripsi">Deskripsi</label>
                            <textarea name="body" id="text" class="form-control"  placeholder="Isi dengan biodata anda">{{ $anggotas->body }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="foto">Foto Anggota</label>
                            <input type="file" name="foto_anggota" class="form-control"></input>
                            <br>
                            <label for="gambar">Foto Saat Ini</label><br>
                            <img src="{{ asset('storage/'. $anggotas->foto_anggota) }}" width="100">
                        </div>
                        <div class="form-group">
                        <div class="form-group">
                        <button class="btn btn-primary btn-sm" type="submit">Save</button>
                        <button class="btn btn-danger btn-sm" type="reset">Reset</button>
                        </div>
                    </form>
				</div>
            </div>
        </div>
</div>

@endsection

resources/views/anggota/index.blade.php
@extends('layouts.master')

@section('title', 'Anggota')

@section('content')

@if (session('success'))
<div class="alert alert-success">
    {{ session('success') }}
</div>
@endif

<div class="panel-header bg-primary-gradient">
    <div class="page-inner py-5">
        <div class="d-flex align-items-left align-items-md-center flex-column flex-md-row">
            <div>

            </div>
            <div class="ml-md-auto py-2 py-md-0">
            </div>
        </div>
    </div>
</div>

<div class="page-inner mt--5">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="card-head-row">
                        <div class="card-title">Daftar Anggota</div>
                        @can('create')
                        <a href="{{ route('anggota.create') }}" class="btn btn-primary btn-sm ml-auto">Ceate</a>
                        @endcan
                    </div>
                    <a href="{{ route('anggota.cetakpdf' ) }}" target="_blank"  class="btn btn-success btn-sm ml-auto">Cetak PDF <i class="fas fa-print"></i></a>
                    <a href="{{ route('anggota.cetakexcel' ) }}" target="_blank"  class="btn btn-primary btn-sm ml-auto">Cetak EXCEL <i class="fas fa-print"></i></a>
                    {{-- <a class="btn btn-primary" href="{{ ('anggota/cetak_pdf') }}">Export to PDF</a> --}}
                </div>
                <div class="card-body">
                    @if (Session::has('success'))
                    <div class="alert alert-success">
                        {{ Session('success') }}
                    </div>
                    @endif
                    <div class="table-responsive">
                        <table class="table table-border">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Nama Anggota</th>
                                    <th>Jabatan</th>
                                    <th>Deskripsi</th>
                                    <th>Gambar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($anggotas as $index => $row)
                                <tr>
                                    <td>{{ $index + $anggotas->firstItem() }}</td>
                                    <td>{{ $row->nama }}</td>
                                    <td>{{ $row->jabatan }}</td>
                                    <td>{{ $row->body }}</td>
                                    <td><img src="{{ asset('storage/'. $row->foto_anggota) }}" width="100"></td>
                                    <td>
                                        @can('edit')
                                        <a href="{{ route('anggota.edit', $row->id) }}"
                                            class="btn btn-warning btn-sm"><i class="fas fa-pen"></i>
                                        </a>
                                        @endcan

                                        @can('delete')
                                        <form action="{{ route('anggota.destroy', $row->id) }}" method="POST" class="d-inline">
                                            @csrf
                                            @method('delete')
                                            <button class="btn btn-danger btn-sm">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                        @endcan

                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="6" class="text-center">Data Masih Kosong</td>
                                </tr>
                                @endforelse

                            </tbody>
                        </table>
                    </div>
                    {{ $anggotas->links() }}

                </div>
            </div>
        </div>
    </div>


    @endsection